### ISSUE TITLE
nodenv.sh file line endings

### ISSUE THREAD

**Issue by eelcodevlieger** [openfoodfoundation/ofn-devbox#2]
Host Operating System: Windows 10

During task 'install node 5.12.0' I received the following exception:

> "**stderr**": "/etc/profile.d/nodenv.sh: line 5: syntax error: unexpected end of file\nbash: nodenv: command not found"

I ran the following command to fix this locally.
```
$ dos2unix.exe setup/nodenv.sh
dos2unix: converting file setup/nodenv.sh to Unix format...
```

Perhaps this was due to my git line ending config.
```
$ git config --list
core.autocrlf=true
```

**Comment by Matt-Yorkley** [comment]
Interesting, I'll take a look at it now. What OS are you using @eelcodevlieger?

**Comment by lin-d-hop** [comment]
Win10, no? First line...

**Comment by Matt-Yorkley** [comment]
Thanks for being the first Windows guineapig,  @eelcodevlieger! Looks like your custom setting changes the line ending when a file is checked out, and this causes a bit of a Windows/Linux encoding clash when some of the setup files are pushed into the Ubuntu VM. 

I've created a new branch called `line_endings` that should fix it. Could you pull the branch and try it out? Thanks!

It adds this file in the root of the directory, which should partially override any settings and resolve the issue: https://github.com/openfoodfoundation/ofn-devbox/blob/line_endings/.gitattributes

**Comment by eelcodevlieger** [comment]
I did a fresh checkout of the line_endings branch. Unfortunately I'm still seeing the same issue. Not sure why the .gitattributes eol change isn't working for me.

This might be a useful option in the shell type provision step in the Vagrantfile?

```
binary (boolean) - Vagrant automatically replaces Windows line endings with Unix line endings. If this is false, then Vagrant will not do this. By default this is "false". If the shell provisioner is communicating over WinRM, this defaults to "true".
```
https://www.vagrantup.com/docs/provisioning/shell.html

**Comment by Matt-Yorkley** [comment]
That's a nice option to know! The nodenv script is not running in the shell provisioning block though, and it looks like Vagrant's local_ansible provisioner doesn't have the same option.

**Comment by Matt-Yorkley** [comment]
I've run out of time today, so I'll have to look at it another time. As far as I can tell, that `.gitattributes` file should work, but it might just effect subsequent changes and not your current files? I'd try doing `git reset --hard upstream/line_endings` or running your `dos2unix.exe` converter on it again, and see if it's fixed on subsequent checkouts?

You could also try changing your setting to `core.autocrlf=input`.

**Comment by eelcodevlieger** [comment]
I had another play with this.

I think the config is being picked up OK, in that it prevents windows Git replacing LF line endings with CRLF.

Looking at branch master, I see
setup/provision.yml **CRLF**
setup/application.yml **CRLF**

Looking at the same files in checked out branch 'line endings', I see
setup/provision.yml **LF**
setup/application.yml **CRLF**

This suggests to me that the file application.yml might be committed with CRLF line endings, I would assume the same is true for the nodenv.sh file.

I confirmed this by converting the nodenv.sh file line endings to LF and committing it to my forked repo. A fresh clone showed that the LF line endings were preserved on checkout and 'vagrant up' managed to execute the 'install node 5.12.0' task successfully.
https://github.com/eelcodevlieger/ofn-devbox/commit/e74200086e9e2f192b09d9c4ab3bbc1b42c486b8

**Comment by Matt-Yorkley** [comment]
I have a feeling the yml files are not an issue because they are read rather than executed...

**Comment by eelcodevlieger** [comment]
> I have a feeling the yml files are not an issue because they are read rather than executed...

agreed, I just used the yml files to show that the .gitattributes config line was picked up OK
```
*.yml text eol=lf
```

**Comment by Matt-Yorkley** [comment]
Addressed in PR #4.
